# Generated by Django 5.1.4 on 2024-12-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infonow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/article'),
        ),
    ]
